root: ./

structure:  
    readme: README.md  
    summary: SUMMARY.md

redirects:  
    10-custom-urls: ./kb/using-deadline-funnel/custom-urls.md
    628-getting-started: ./deadline-funnel/the-basics/getting-started.md
    help/contact: ./contact.md
